name: Create GitHub release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+[a-c][0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-c][0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build-viewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Clone BioNGFF Viewer
        run: git clone https://github.com/BioNGFF/biongff-viewer.git

      - name: Init git submodules
        run: |
          cd biongff-viewer
          git submodule init
          git submodule update

      - name: Generate build artifacts
        run: |
          cd biongff-viewer
          npx pnpm install
          npx pnpm --filter viewer run build
          npx pnpm --filter anndata-zarr run build
          npx pnpm --filter app run build --base './'

      - name: Generate the package
        run: |
          cd biongff-viewer
          mv sites/app/dist .
          tar -czpf fractal-viewer-${{ github.ref_name }}.tar.gz dist LICENSE

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: biongff-viewer/fractal-viewer-${{ github.ref_name }}.tar.gz

  build-vizarr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Clone vizarr
        run: git clone https://github.com/fractal-analytics-platform/vizarr.git

      - name: Checkout vizarr commit
        run: |
          cd vizarr
          git checkout a70efd2f2861ed7e20d6485525806799a6d9f619

      - name: Install dependencies
        run: |
          cd vizarr
          npx -y pnpm install

      - name: Generate build artifacts
        run: |
          cd vizarr
          npx pnpm run build

      - name: Generate the package
        run: |
          cd vizarr
          tar -czpf fractal-vizarr-${{ github.ref_name }}.tar.gz dist LICENSE

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: vizarr/fractal-vizarr-${{ github.ref_name }}.tar.gz

  build-server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18', '20']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Generate build artifacts
        run: npm run build

      - name: Generate the package
        run: npm pack

      - name: Extract the package
        run: tar -xzf fractal-data-*.tgz

      - name: Repack the package removing parent folder
        run: tar -C package -czf node-${{ matrix.node-version }}-fractal-data-${{ github.ref_name }}.tar.gz dist package.json node_modules LICENSE

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: node-${{ matrix.node-version }}-fractal-data-${{ github.ref_name }}.tar.gz
